name: code-quality
run-name: 🖌️ Qualidade de código
on: 
  workflow_dispatch: 
  push:
    branches:
      - master
  pull_request: 
    branches:
      - master
jobs:
  static_analysis:
    name: 🕵️ Análise estática
    runs-on: ubuntu-latest
    steps:
      - name: 📦 Checkout
        uses: actions/checkout@v4
      - name: 📦 Setup do Node.js
        uses: actions/setup-node@v4
      - name: 📦 Setup do Yarn
        run: npm install -g yarn
      - name: 📦 Instalar dependências
        run: yarn install
      - name: 🕵️ Executa o ESLint
        run: yarn lint
      - name: 🕵️ Executa o Shift Left Security
        uses: ShiftLeftSecurity/scan-action@master
        env:
          WORKSPACE: https://github.com/${{ github.repository }}/blob/${{ github.sha }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 🆙 Upload resultado do Shift Left Security
        uses: actions/upload-artifact@v2
        with:
          name: shift-left-security
          path: reports
  dynamic_analysis:
    name: 🕵️ Análise dinâmica
    runs-on: ubuntu-latest
    steps:
      - name: 📦 Checkout
        uses: actions/checkout@v4
      - name: 📦 Setup do Node.js
        uses: actions/setup-node@v4
      - name: 📦 Setup do Yarn
        run: npm install -g yarn
      - name: 📦 Setup do Docker
        uses: docker-practice/actions-setup-docker@master
        timeout-minutes: 12
      - name: 🐋 Rodar Docker Compose
        run: docker-compose -f docker-compose.yml up -d
      - name: 📦 Instalar dependências
        run: yarn install
      - name: 🔐 Gera o arquivo .env
        run: |
          echo "NEXT_PUBLIC_SERVER_URL=http://localhost:3000" >> .env
          echo "MONGODB_URL=mongodb://mongo:mongo@localhost:27017/" >> .env
          echo "PAYLOAD_SECRET=${{ secrets.PAYLOAD_SECRET }}" >> .env
          echo "STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }}" >> .env
          echo "STRIPE_WEBHOOK_SECRET=${{ secrets.STRIPE_WEBHOOK_SECRET }}" >> .env
          echo "RESEND_API_KEY=${{ secrets.RESEND_API_KEY }}" >> .env
      - name: 🛠️ Fazer o build da aplicação
        run: yarn build
      - name: 🛠️ Executa a aplicação em background
        uses: JarvusInnovations/background-action@v1
        with:
          run: |
            yarn start &
          wait-on: |
            http-get://localhost:3000
      - name: 🕵️ Executa o ZaProxy
        uses: zaproxy/action-full-scan@v0.10.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: ghcr.io/zaproxy/zaproxy:stable
          target: http://localhost:3000
          rules_file_name: .zap/rules.tsv
          cmd_options: -a -z "-config view.locale=pt_BR"
